# Generated by Django 4.2.17 on 2025-02-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Скидка в процентах'),
        ),
        migrations.AlterField(
            model_name='products',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media_goods/', verbose_name='Изображение'),
        ),
    ]
